### ISSUE TITLE
xmlstarlet?

### ISSUE THREAD

**Issue by zvezdochiot** [plzombie/depress#7]
Hi @plzombie .

Ежели пользовать [xmlstarlet](http://xmlstar.sourceforge.net/), то проекты очень красивенькие получаются:

Оригинал:
``` shell
depress/test$ cat test.died
```
``` xml
<Document>
<DocumentFlags ptt="1" ptt_flags="1" />
<Flags type="1" param1="2" quality="100" dpi="100" />
<Pages>
<Page><Filename>unicodeexample😊.jpg</Filename></Page>
<Page><Filename>unicodeexample⁂.jpg</Filename></Page>
<Page><Filename>unicodeexample❤.jpg</Filename></Page>
<Page><Filename>unicodeexample☺.jpg</Filename></Page>
<Page><Flags type="0" param1="0" quality="80" dpi="100" /><Filename>unicodeexample😊.jpg</Filename></Page>
<Page><Flags type="1" param1="2" quality="100" dpi="100" /><Filename>mask_test.png</Filename><IllRect x="128" y="64" width="256" height="256" /></Page>
</Pages>
</Document>
```

Форматирование+валидация:
``` shell
depress/test$ xmlstarlet fo -R test.died >test.died.x
```

Результат:
``` shell
depress/test$ cat test.died.x
```
``` xml
<?xml version="1.0"?>
<Document>
  <DocumentFlags ptt="1" ptt_flags="1"/>
  <Flags type="1" param1="2" quality="100" dpi="100"/>
  <Pages>
    <Page>
      <Filename>unicodeexample&#x1F60A;.jpg</Filename>
    </Page>
    <Page>
      <Filename>unicodeexample&#x2042;.jpg</Filename>
    </Page>
    <Page>
      <Filename>unicodeexample&#x2764;.jpg</Filename>
    </Page>
    <Page>
      <Filename>unicodeexample&#x263A;.jpg</Filename>
    </Page>
    <Page>
      <Flags type="0" param1="0" quality="80" dpi="100"/>
      <Filename>unicodeexample&#x1F60A;.jpg</Filename>
    </Page>
    <Page>
      <Flags type="1" param1="2" quality="100" dpi="100"/>
      <Filename>mask_test.png</Filename>
      <IllRect x="128" y="64" width="256" height="256"/>
    </Page>
  </Pages>
</Document>
```

**Comment by plzombie** [comment]
Это всё хорошо, блоки с табуляцией, только зачем он мне символы юникода экранировал? С ними даже под виндой проблем нет

**Comment by zvezdochiot** [comment]
@plzombie say:
>проблем нет

А с экранированными какие то проблемы?

**Comment by plzombie** [comment]
Мне как пользователю непонятно что там. А программе в принципе плевать на форматирование и в каком виде там символы

**Comment by zvezdochiot** [comment]
@plzombie say:
>Мне как пользователю

Не ври себе, ты не пользователь. А пользователь кроме ГУИшки разве что-нибудь увидит?

**Comment by plzombie** [comment]
Я эти xml редактировал руками в блокноте, значит пользователь. Ну и в чём тогда смысл использовать xml, если нельзя залезть руками и подправить?

**Comment by zvezdochiot** [comment]
@plzombie say:
>Я эти xml редактировал руками в блокноте

Вот оно как оказывается! А что ж ты в консольную то версию парсинг XML не встроил? Ну коли один чорт "проект" ни разу не ГУИшный?

**Comment by plzombie** [comment]
У меня проект, записанный программой на диск, выглядит вот так. Одной строчкой.
![изображение](https://user-images.githubusercontent.com/1690651/215965816-df8f7dc7-b124-40cd-92cd-862d97378400.png)
Для кого мне экранирования символов вставлять? Программе на них плевать. А пользователю - только хуже делать

**Comment by zvezdochiot** [comment]
@plzombie say:
>Одной строчкой.

Ну так ты нормальный редактор пользуй, например [Notepad++](https://notepad-plus-plus.org/). Большинство виндовых поделок ни Unix-лине, ни Mac-лине не "понимают". Это как раз этот случай.

**Comment by plzombie** [comment]
Оно отображается одной строкой, потому что оно записано на диск одной строкой, без LF

**Comment by zvezdochiot** [comment]
@plzombie say:
>потому что оно записано на диск одной строкой

Ну так знать не зря я на [xmlstalet](http://xmlstar.sourceforge.net/) ссылочку выложил. При таких "пирожках", оно самое то!
